-- Sync updated FAQ and Rules for Futuristic Run and Futuristic Bike into event_settings
INSERT INTO public.event_settings (event_type, key, value) VALUES
  ('futuristic-run', 'faq', 'Kapan dan di mana tepatnya Futuristic Run 2026? | Futuristic Run diselenggarakan pada Sabtu malam, 1 Agustus 2026. Open gate dimulai pukul 18.00 WIB, dengan lokasi Start dan Finish di Alun-Alun Purworejo.
Berapa jarak tempuh rute dan batas waktu penyelesaiannya? | Jarak lari resmi adalah 5 kilometer (5K Road Run) dengan batas waktu penyelesaian (Cut Off Time / COT) selama 90 menit (1,5 jam). Rute didesain flat dan ramah bagi pemula maupun pelari prestasi.
Berapa biaya pendaftaran dan apa saja benefit kepesertaan? | Biaya pendaftaran Presale 1 Rp120.000 (100 pendaftar pertama) dan Harga Normal Rp135.000. Benefit mencakup: Jersey lari eksklusif, Nomor BIB, Medali Finisher, E-Sertifikat, refreshment (air mineral & isotonik), kupon doorprize utama, serta hiburan live music.
Bagaimana alur pembayaran dan verifikasi pendaftaran? | Pendaftaran dilakukan online melalui situs resmi. Pembayaran via Transfer Bank (BRI), DANA, atau QRIS. Setelah mengunggah bukti pembayaran, tim admin akan melakukan verifikasi maksimal 1x24 jam. Status dapat dicek secara berkala di halaman Cek Tiket.
Apakah tersedia hadiah uang tunai untuk pemenang? | Ya! Tersedia total hadiah jutaan rupiah serta trofi eksklusif yang dibagi ke dalam beberapa kategori podium (Juara Umum 1-3 & Harapan 1-2 Putra/Putri, serta Juara Pelajar SD/SMP/SMA).
Kapan jadwal pengambilan Race Pack (RPC)? | Pengambilan Race Pack Collection dijadwalkan bertempat di Kampus Plaosan sebelum hari H. Jadwal resmi dan persyaratan dokumen pengambilan akan diinformasikan melalui akun WhatsApp terverifikasi.'),
  ('futuristic-run', 'rules', '01. Registrasi & Identitas | Peserta wajib mendaftar menggunakan identitas asli (KTP/KIA/Kartu Pelajar/SIM) yang sah dan masih berlaku. • Pendaftaran baru dinyatakan sah setelah peserta melakukan pembayaran dan diverifikasi oleh admin. • Biaya pendaftaran yang sudah dibayarkan tidak dapat dikembalikan (non-refundable) ataupun dipindahtangankan tanpa persetujuan tertulis dari panitia.
02. Kesiapan Fisik & Medis | Peserta wajib berada dalam kondisi sehat jasmani dan rohani untuk menyelesaikan jarak lari 5 kilometer. • Peserta yang memiliki riwayat penyakit medis khusus (seperti gangguan jantung atau asma berat) disarankan berkonsultasi dengan dokter terlebih dahulu. • Tim medis berhak menghentikan peserta di jalur lari apabila dinilai tidak layak atau membahayakan keselamatan diri sendiri.
03. Regulasi Nomor BIB | Nomor BIB wajib dipasang di bagian depan dada atau perut sehingga jelas terlihat oleh marshal dan kamera juri sepanjang lintasan. • Larangan keras melipat, menutupi, atau memodifikasi nomor BIB. • Penggunaan nomor BIB milik orang lain atau pemalsuan BIB akan mengakibatkan diskualifikasi seketika.
04. Tata Tertib Rute & Water Station | Peserta wajib berlari sesuai rute resmi yang telah ditentukan oleh panitia. Memotong jalan (shortcut) akan langsung mendiskualifikasi peserta dari perolehan podium. • Peserta wajib mematuhi arahan marshal dan petugas lalu lintas di sepanjang jalur. • Tersedia fasilitas Water Station di titik kilometer 2.5 dan area Finish. Dilarang membuang sampah cangkir atau botol sembarangan di luar zona yang disediakan.
05. Pengambilan Race Pack (RPC) | Pengambilan Race Pack wajib menyertakan E-Ticket (QR Code dari email/situs) dan kartu identitas asli. • Pengambilan yang diwakilkan wajib menyertakan surat kuasa bermaterai dan fotokopi identitas pemilik tiket. • Panitia tidak melayani pengambilan Race Pack di luar jadwal dan lokasi yang telah ditentukan.
06. Force Majeure & Keputusan Mutlak | Dalam keadaan darurat (bencana alam, badai ekstrem, kerusuhan, atau instruksi otoritas keamanan), panitia berhak membatalkan, menunda, atau mengubah rute kegiatan demi keselamatan bersama. • Seluruh keputusan juri dan panitia terkait waktu finish, penentuan pemenang podium, dan diskualifikasi bersifat mutlak serta tidak dapat diganggu gugat.'),
  ('fun-bike', 'faq', 'Kapan dan di mana pelaksanaan Futuristic Bike 2026? | Futuristic Bike dilaksanakan pada Minggu pagi, 2 Agustus 2026. Berkumpul mulai pukul 05.00 WIB (menikmati suasana sunrise), dengan titik Start dan Finish di Alun-Alun Purworejo.
Apakah acara ini merupakan lomba balap sepeda adu kecepatan? | Bukan. Futuristic Bike adalah kegiatan Fun Ride bertema santai kebersamaan dan gaya hidup sehat menyambut matahari terbit. Tidak ada pencatatan waktu finish tercepat.
Berapa biaya pendaftaran dan apa saja fasilitas yang didapatkan? | Biaya pendaftaran adalah Rp150.000. Fasilitas peserta mencakup: Jersey bersepeda eksklusif edisi Sunrise, Nomor Sepeda (Bike Number), E-Sertifikat, kupon undian Grand Prize & Doorprize menarik, refreshment pagi, pengawalan marshal, dan posko medis.
Jenis sepeda apa saja yang diperbolehkan untuk ikut serta? | Terbuka untuk berbagai jenis sepeda non-mesin, antara lain Road Bike, Mountain Bike (MTB), Sepeda Lipat (Seli), Sepeda Gravel, hingga Sepeda Mini/Onthel, selama dalam kondisi laik jalan dan sistem pengereman berfungsi sempurna.
Bagaimana gambaran rute yang akan dilalui peserta? | Rute menempuh jarak santai mengelilingi landmark bersejarah dan area perkotaan Purworejo dengan pengawalan Road Captain dan kepolisian. Detail rute final dan pos istirahat (pitstop) akan diinformasikan saat Technical Meeting.
Apakah anak-anak atau keluarga boleh menjadi peserta? | Sangat boleh! Acara ini ramah keluarga. Namun, peserta di bawah usia 15 tahun wajib didampingi oleh orang tua atau wali dewasa sepanjang perjalanan demi keamanan berkendara di jalan raya.'),
  ('fun-bike', 'rules', '01. Pendaftaran & Identitas | Peserta wajib mendaftar dengan identitas asli yang sah. • Pendaftaran baru dianggap selesai setelah bukti transfer diverifikasi oleh admin. • Satu tiket kepesertaan berlaku untuk satu orang dan satu sepeda. Tiket tidak dapat dikembalikan (non-refundable).
02. Kelayakan Sepeda | Peserta wajib menggunakan sepeda dalam kondisi prima dan laik jalan. • Sistem pengereman (rem depan dan belakang) wajib berfungsi sempurna sebelum garis start. • Penggunaan sepeda listrik (e-bike/full throttle) atau sepeda bermotor tidak diperkenankan untuk menjaga kesetaraan rombongan Fun Ride.
03. Keselamatan Berkendara (Safety First) | Peserta SANGAT DIWAJIBKAN menggunakan helm bersepeda (cycling helmet) dan sepatu tertutup demi keselamatan pribadi. • Peserta disarankan mengenakan pakaian atau aksesori yang mudah terlihat (reflective). • Dilarang keras melakukan atraksi berbahaya (zig-zag ekstrim, lepas tangan, atau ngebut melepasi Road Captain terdepan).
04. Ketertiban Rute & Rombongan | Wajib mematuhi rambu lalu lintas dan arahan dari Marshal / Road Captain pengawal rombongan. • Peserta wajib bergerak di lajur kiri jalan dan memberi ruang bagi kendaraan umum atau darurat (ambulans/pemadam kebakaran). • Dilarang tertinggal di belakang kendaraan sweeper (sapu jagat) tanpa memberi tahu marshal.
05. Pengawasan Anak & Fasilitas Drop Bag | Peserta anak-anak di bawah usia 15 tahun sepenuhnya berada di bawah pengawasan dan tanggung jawab orang tua/wali pendamping. • Panitia menyediakan tenda penitipan barang (drop bag) gratis di area Alun-Alun, namun peserta dilarang meninggalkan barang berharga (perhiasan/elektronik mahal).
06. Force Majeure & Keputusan Panitia | Apabila terjadi kondisi cuaca buruk yang membahayakan (hujan badai petir) atau kejadian darurat di luar kendali, panitia berhak memperpendek rute atau menghentikan acara. • Ketentuan panitia demi ketertiban dan keselamatan umum bersifat mengikat bagi seluruh peserta.')
ON CONFLICT (event_type, key) DO UPDATE
SET value = EXCLUDED.value,
    updated_at = NOW();
